"""Normalizacao de generos entre fontes.

Cada fonte usa vocabulario proprio: MangaDex fala "Action"/"Slice of Life",
sites Madara falam "Acao"/"Slice Of Life". O catalogo unifica no slug canonic
para filtro e exibicao consistentes entre resultados.
"""

from __future__ import annotations

# slug -> rotulo em portugues (o que o frontend mostra)
CANONICAL: dict[str, str] = {
    "action": "Ação",
    "adventure": "Aventura",
    "comedy": "Comédia",
    "drama": "Drama",
    "fantasy": "Fantasia",
    "horror": "Horror",
    "mystery": "Mistério",
    "psychological": "Psicológico",
    "romance": "Romance",
    "sci-fi": "Ficção Científica",
    "slice-of-life": "Slice of Life",
    "sports": "Esportes",
    "supernatural": "Sobrenatural",
    "thriller": "Thriller",
    "tragedy": "Tragédia",
    "isekai": "Isekai",
    "mecha": "Mecha",
    "historical": "Histórico",
    "martial-arts": "Artes Marciais",
    "school-life": "Vida Escolar",
    "shounen": "Shounen",
    "shoujo": "Shoujo",
    "seinen": "Seinen",
    "josei": "Josei",
    "yaoi": "Yaoi",
    "yuri": "Yuri",
    "ecchi": "Ecchi",
    "harem": "Harem",
    "gender-bender": "Gender Bender",
    "magical-girls": "Mahou Shoujo",
    "medical": "Médico",
    "music": "Música",
    "philosophical": "Filosófico",
    "crime": "Crime",
    "wuxia": "Wuxia",
    "cooking": "Culinária",
    "video-games": "Video Games",
    "superhero": "Super-herói",
    "military": "Militar",
    "police": "Policial",
    "post-apocalyptic": "Pós-apocalíptico",
    "survival": "Sobrevivência",
    "office": "Escritório",
    "animals": "Animais",
    "delinquents": "Delinquentes",
    "monsters": "Monstros",
    "reincarnation": "Reencarnação",
    "time-travel": "Viagem no Tempo",
    "vampires": "Vampiros",
    "zombies": "Zumbis",
    "demons": "Demônios",
    "magic": "Magia",
    "ninja": "Ninja",
    "samurai": "Samurai",
    "virtual-reality": "Realidade Virtual",
    "crossdressing": "Crossdressing",
    "full-color": "Colorido",
    "oneshot": "One-shot",
    "doujinshi": "Doujinshi",
    "webtoon": "Webtoon",
    "adaptation": "Adaptação",
    "anthology": "Antologia",
    "award-winning": "Premiado",
    "fan-colored": "Colorido por fãs",
    "official-colored": "Colorido oficial",
    "long-strip": "Tira vertical",
    "4-koma": "4-koma",
    "user-created": "Criado por usuário",
}

# alias bruto (ja lowercased) -> slug canonic
_ALIASES: dict[str, str] = {
    # ingles / mangadex
    "action": "action",
    "adventure": "adventure",
    "comedy": "comedy",
    "drama": "drama",
    "fantasy": "fantasy",
    "horror": "horror",
    "mystery": "mystery",
    "psychological": "psychological",
    "romance": "romance",
    "sci-fi": "sci-fi",
    "science fiction": "sci-fi",
    "slice of life": "slice-of-life",
    "sports": "sports",
    "supernatural": "supernatural",
    "thriller": "thriller",
    "tragedy": "tragedy",
    "isekai": "isekai",
    "mecha": "mecha",
    "historical": "historical",
    "martial arts": "martial-arts",
    "school life": "school-life",
    "boys' love": "yaoi",
    "boys love": "yaoi",
    "girls' love": "yuri",
    "girls love": "yuri",
    "shounen": "shounen",
    "shonen": "shounen",
    "shoujo": "shoujo",
    "shojo": "shoujo",
    "seinen": "seinen",
    "josei": "josei",
    "yaoi": "yaoi",
    "yuri": "yuri",
    "ecchi": "ecchi",
    "harem": "harem",
    "gender bender": "gender-bender",
    "magical girls": "magical-girls",
    "medical": "medical",
    "music": "music",
    "philosophical": "philosophical",
    "crime": "crime",
    "wuxia": "wuxia",
    "cooking": "cooking",
    "video games": "video-games",
    "superhero": "superhero",
    "military": "military",
    "police": "police",
    "post-apocalyptic": "post-apocalyptic",
    "survival": "survival",
    "office": "office",
    "office workers": "office",
    "animals": "animals",
    "delinquents": "delinquents",
    "monsters": "monsters",
    "reincarnation": "reincarnation",
    "time travel": "time-travel",
    "vampires": "vampires",
    "zombies": "zombies",
    "demons": "demons",
    "magic": "magic",
    "ninja": "ninja",
    "samurai": "samurai",
    "virtual reality": "virtual-reality",
    "crossdressing": "crossdressing",
    "full color": "full-color",
    "oneshot": "oneshot",
    "one shot": "oneshot",
    "doujinshi": "doujinshi",
    "webtoon": "webtoon",
    "adaptation": "adaptation",
    "anthology": "anthology",
    "award winning": "award-winning",
    "fan colored": "fan-colored",
    "official colored": "official-colored",
    "long strip": "long-strip",
    "4-koma": "4-koma",
    "4 koma": "4-koma",
    "user created": "user-created",
    # portugues / madara
    "acao": "action",
    "ação": "action",
    "aventura": "adventure",
    "comedia": "comedy",
    "comédia": "comedy",
    "fantasia": "fantasy",
    "misterio": "mystery",
    "mistério": "mystery",
    "psicologico": "psychological",
    "psicológico": "psychological",
    "ficcao cientifica": "sci-fi",
    "ficção científica": "sci-fi",
    "esportes": "sports",
    "esporte": "sports",
    "sobrenatural": "supernatural",
    "tragedia": "tragedy",
    "tragédia": "tragedy",
    "historico": "historical",
    "histórico": "historical",
    "artes marciais": "martial-arts",
    "vida escolar": "school-life",
    "escola": "school-life",
    "shônen": "shounen",
    "shôjo": "shoujo",
    "harém": "harem",
    "culinaria": "cooking",
    "culinária": "cooking",
    "super heroi": "superhero",
    "super-herói": "superhero",
    "militar": "military",
    "policial": "police",
    "pos-apocaliptico": "post-apocalyptic",
    "pós-apocalíptico": "post-apocalyptic",
    "sobrevivencia": "survival",
    "sobrevivência": "survival",
    "reencarnacao": "reincarnation",
    "reencarnação": "reincarnation",
    "viagem no tempo": "time-travel",
    "vampiros": "vampires",
    "zumbis": "zombies",
    "demonios": "demons",
    "demônios": "demons",
    "magia": "magic",
    "realidade virtual": "virtual-reality",
    "colorido": "full-color",
    "one-shot": "oneshot",
}


def normalize_genre(raw: str) -> str | None:
    """Converte o rotulo bruto da fonte no slug canonic, ou None se desconhecido."""
    key = " ".join(raw.strip().lower().split())
    if not key:
        return None
    return _ALIASES.get(key)


def normalize_genres(raw: list[str], limit: int = 12) -> list[str]:
    """Devolve slugs unicos na ordem de entrada, limitados."""
    seen: set[str] = set()
    out: list[str] = []
    for item in raw:
        slug = normalize_genre(item)
        if slug and slug not in seen:
            seen.add(slug)
            out.append(slug)
            if len(out) >= limit:
                break
    return out


def label_for(slug: str) -> str:
    return CANONICAL.get(slug, slug)
